'use client'

import { useState, useEffect } from 'react';
import Link from 'next/link';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle, DialogTrigger } from '@/components/ui/dialog';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { TrendingUp, TrendingDown, Mail, Crown, Target, Zap, ExternalLink, CheckCircle2, AlertTriangle } from 'lucide-react';
import { toast } from 'sonner';

export default function TulipCommandCenter() {
  const [competitors, setCompetitors] = useState([]);
  const [signals, setSignals] = useState([]);
  const [loading, setLoading] = useState(true);
  const [emailDialogOpen, setEmailDialogOpen] = useState(false);
  const [emailRecipients, setEmailRecipients] = useState('leadership-team@tulip.co');
  const [sendingEmail, setSendingEmail] = useState(false);

  useEffect(() => {
    loadData();
  }, []);

  async function loadData() {
    try {
      const [competitorsRes, signalsRes] = await Promise.all([
        fetch('/api/competitors'),
        fetch('/api/signals')
      ]);
      
      setCompetitors(await competitorsRes.json());
      setSignals(await signalsRes.json());
    } catch (error) {
      console.error('Error loading data:', error);
      toast.error('Failed to load data');
    } finally {
      setLoading(false);
    }
  }

  async function sendWeeklyDigest() {
    setSendingEmail(true);
    
    // Generate comprehensive digest
    const tulip = competitors.find(c => c.id === 'tulip');
    const competitorsOnly = competitors.filter(c => c.id !== 'tulip');
    const highThreatCompetitors = competitorsOnly.filter(c => c.threatLevel === 'high');
    const recentSignals = signals.filter(s => {
      const signalDate = new Date(s.timestamp);
      const weekAgo = new Date();
      weekAgo.setDate(weekAgo.getDate() - 7);
      return signalDate > weekAgo;
    });

    const emailSubject = `Weekly Competitive Intelligence Digest - ${new Date().toLocaleDateString()}`;
    const emailBody = `TULIP COMPETITIVE INTELLIGENCE - WEEKLY DIGEST
${new Date().toLocaleDateString()}

═══════════════════════════════════════════════
📊 TULIP MARKET POSITION
═══════════════════════════════════════════════

✓ Valuation: ${tulip?.valuation} (UNICORN STATUS)
✓ Revenue: ${tulip?.revenue}
✓ Employees: ${tulip?.employees}
✓ Market Rank: #3 by revenue in frontline operations
✓ Funding: ${tulip?.funding}
✓ Recent: Acquired Akooda for AI (Nov 2025)

═══════════════════════════════════════════════
🎯 COMPETITIVE LANDSCAPE (Top 5 Competitors)
═══════════════════════════════════════════════

${competitorsOnly.slice(0, 5).map((c, idx) => `
${idx + 1}. ${c.name} (${c.category})
   Revenue: ${c.revenue}
   Threat Level: ${c.threatLevel?.toUpperCase() || 'LOW'}
   Employees: ${c.employees}
   Status: ${c.valuation || 'Private'}
`).join('')}

═══════════════════════════════════════════════
⚠️  HIGH-PRIORITY THREATS
═══════════════════════════════════════════════

${highThreatCompetitors.length > 0 ? highThreatCompetitors.map(c => `
• ${c.name}
  Why: ${c.positioning.substring(0, 150)}...
  Action: Monitor closely, update battlecards
`).join('') : 'No high-priority threats this week.'}

═══════════════════════════════════════════════
📰 NEW COMPETITIVE SIGNALS (Last 7 Days)
═══════════════════════════════════════════════

${recentSignals.length > 0 ? recentSignals.map(s => `
• [${s.severity.toUpperCase()}] ${s.competitorName}: ${s.title}
  ${s.summary.substring(0, 120)}...
  Recommended: ${s.recommendedAction.substring(0, 100)}...
`).join('') : 'No new signals in the past week.'}

═══════════════════════════════════════════════
📈 KEY INSIGHTS & RECOMMENDATIONS
═══════════════════════════════════════════════

1. Market Position: Tulip maintains #3 position with unicorn status
2. Funding Advantage: $272.5M vs competitors averaging $100M
3. AI Leadership: Most comprehensive AI suite (Composer + Agents + Akooda)
4. Growth Momentum: Recent Series D validates market opportunity
5. Watch: Apprentice.io (54% YoY growth in pharma vertical)

═══════════════════════════════════════════════
🔗 TAKE ACTION
═══════════════════════════════════════════════

View Full Dashboard:
${window.location.origin}/tulip-command-center

Generate Battlecards:
${window.location.origin}/battlecard

View All Signals:
${window.location.origin}/signals

---
Generated by Tulip Competitive Intelligence Command Center
For questions, contact your competitive intelligence team.
`;

    // Create mailto link
    const mailtoUrl = `mailto:${emailRecipients}?subject=${encodeURIComponent(emailSubject)}&body=${encodeURIComponent(emailBody)}`;
    
    window.location.href = mailtoUrl;
    toast.success('Opening email client with weekly digest...');
    
    setSendingEmail(false);
    setEmailDialogOpen(false);
  }

  if (loading) {
    return (
      <div className="flex items-center justify-center min-h-screen">
        <div className="text-center">
          <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-primary mx-auto"></div>
          <p className="mt-4 text-muted-foreground">Loading Tulip Command Center...</p>
        </div>
      </div>
    );
  }

  const tulip = competitors.find(c => c.id === 'tulip');
  const competitorsOnly = competitors.filter(c => c.id !== 'tulip').sort((a, b) => {
    const aRev = parseFloat(a.revenue.replace(/[^0-9.]/g, '')) || 0;
    const bRev = parseFloat(b.revenue.replace(/[^0-9.]/g, '')) || 0;
    return bRev - aRev;
  });

  const marketRank = competitorsOnly.filter(c => {
    const cRev = parseFloat(c.revenue.replace(/[^0-9.]/g, '')) || 0;
    const tulipRev = parseFloat(tulip?.revenue.replace(/[^0-9.]/g, '')) || 0;
    return cRev > tulipRev;
  }).length + 1;

  return (
    <div className="container mx-auto p-6 space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <div className="flex items-center gap-3">
            <Crown className="h-8 w-8 text-yellow-500" />
            <h1 className="text-4xl font-bold tracking-tight">Tulip Command Center</h1>
          </div>
          <p className="text-muted-foreground mt-2">Executive Competitive Intelligence Dashboard</p>
        </div>
        <Dialog open={emailDialogOpen} onOpenChange={setEmailDialogOpen}>
          <DialogTrigger asChild>
            <Button size="lg">
              <Mail className="mr-2 h-4 w-4" />
              Send Weekly Digest
            </Button>
          </DialogTrigger>
          <DialogContent>
            <DialogHeader>
              <DialogTitle>Send Weekly Competitive Digest</DialogTitle>
              <DialogDescription>
                Generate and send a comprehensive weekly competitive intelligence report to leadership team
              </DialogDescription>
            </DialogHeader>
            <div className="grid gap-4 py-4">
              <div className="grid gap-2">
                <Label htmlFor="recipients">Email Recipients</Label>
                <Input
                  id="recipients"
                  value={emailRecipients}
                  onChange={(e) => setEmailRecipients(e.target.value)}
                  placeholder="leadership-team@tulip.co"
                />
                <p className="text-xs text-muted-foreground">
                  Separate multiple emails with commas
                </p>
              </div>
              <div className="p-4 bg-muted rounded-lg text-sm">
                <p className="font-semibold mb-2">Digest will include:</p>
                <ul className="space-y-1 text-muted-foreground">
                  <li>✓ Tulip market position & metrics</li>
                  <li>✓ Top 5 competitor overview</li>
                  <li>✓ High-priority threats analysis</li>
                  <li>✓ New signals from past 7 days</li>
                  <li>✓ Key insights & recommendations</li>
                  <li>✓ Quick action links</li>
                </ul>
              </div>
            </div>
            <DialogFooter>
              <Button variant="outline" onClick={() => setEmailDialogOpen(false)}>
                Cancel
              </Button>
              <Button onClick={sendWeeklyDigest} disabled={sendingEmail}>
                {sendingEmail ? 'Generating...' : 'Generate & Send'}
              </Button>
            </DialogFooter>
          </DialogContent>
        </Dialog>
      </div>

      {/* Tulip Status Cards */}
      <div className="grid gap-4 md:grid-cols-4">
        <Card className="border-yellow-500 border-2">
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">Valuation</CardTitle>
            <Crown className="h-4 w-4 text-yellow-500" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold text-yellow-600">{tulip?.valuation}</div>
            <p className="text-xs text-green-600 flex items-center mt-1">
              <TrendingUp className="h-3 w-3 mr-1" />
              Unicorn Status (Jan 2026)
            </p>
          </CardContent>
        </Card>

        <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">Market Rank</CardTitle>
            <Target className="h-4 w-4 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">#{marketRank}</div>
            <p className="text-xs text-muted-foreground">By revenue in category</p>
          </CardContent>
        </Card>

        <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">Revenue (ARR)</CardTitle>
            <TrendingUp className="h-4 w-4 text-green-600" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold text-green-600">{tulip?.revenue}</div>
            <p className="text-xs text-muted-foreground">Fastest growing</p>
          </CardContent>
        </Card>

        <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">Total Funding</CardTitle>
            <Zap className="h-4 w-4 text-blue-600" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold text-blue-600">{tulip?.funding}</div>
            <p className="text-xs text-muted-foreground">Series D (Mitsubishi)</p>
          </CardContent>
        </Card>
      </div>

      {/* Main Comparison */}
      <Tabs defaultValue="snapshot" className="space-y-4">
        <TabsList>
          <TabsTrigger value="snapshot">Market Snapshot</TabsTrigger>
          <TabsTrigger value="comparison">Head-to-Head</TabsTrigger>
          <TabsTrigger value="sources">Data Sources</TabsTrigger>
        </TabsList>

        <TabsContent value="snapshot" className="space-y-4">
          <Card>
            <CardHeader>
              <CardTitle>Tulip vs Market - Competitive Position</CardTitle>
              <CardDescription>
                Real-time comparison with all major competitors
              </CardDescription>
            </CardHeader>
            <CardContent>
              <Table>
                <TableHeader>
                  <TableRow>
                    <TableHead className="w-[200px]">Company</TableHead>
                    <TableHead>Revenue</TableHead>
                    <TableHead>vs Tulip</TableHead>
                    <TableHead>Employees</TableHead>
                    <TableHead>Valuation/Status</TableHead>
                    <TableHead>Threat</TableHead>
                    <TableHead>Action</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  <TableRow className="bg-yellow-50">
                    <TableCell className="font-bold flex items-center gap-2">
                      <Crown className="h-4 w-4 text-yellow-500" />
                      {tulip?.name}
                    </TableCell>
                    <TableCell className="font-bold text-green-600">{tulip?.revenue}</TableCell>
                    <TableCell>
                      <Badge>Reference</Badge>
                    </TableCell>
                    <TableCell>{tulip?.employees}</TableCell>
                    <TableCell className="font-bold text-yellow-600">{tulip?.valuation}</TableCell>
                    <TableCell>-</TableCell>
                    <TableCell>
                      <Link href="/competitors/tulip">
                        <Button size="sm" variant="outline">View Profile</Button>
                      </Link>
                    </TableCell>
                  </TableRow>
                  {competitorsOnly.map((comp) => {
                    const compRev = parseFloat(comp.revenue.replace(/[^0-9.]/g, '')) || 0;
                    const tulipRev = parseFloat(tulip?.revenue.replace(/[^0-9.]/g, '')) || 0;
                    const isAhead = compRev > tulipRev;
                    const diff = Math.abs(compRev - tulipRev).toFixed(1);

                    return (
                      <TableRow key={comp.id}>
                        <TableCell className="font-medium">{comp.name}</TableCell>
                        <TableCell className="font-semibold">{comp.revenue}</TableCell>
                        <TableCell>
                          {isAhead ? (
                            <span className="flex items-center text-red-600 text-sm">
                              <TrendingUp className="h-3 w-3 mr-1" />
                              +${diff}M ahead
                            </span>
                          ) : (
                            <span className="flex items-center text-green-600 text-sm">
                              <TrendingDown className="h-3 w-3 mr-1" />
                              ${diff}M behind
                            </span>
                          )}
                        </TableCell>
                        <TableCell className="text-muted-foreground">{comp.employees}</TableCell>
                        <TableCell className="text-sm">{comp.valuation || 'Private'}</TableCell>
                        <TableCell>
                          <Badge variant="outline" className={
                            comp.threatLevel === 'high' ? 'bg-red-100 text-red-800' :
                            comp.threatLevel === 'medium' ? 'bg-yellow-100 text-yellow-800' :
                            'bg-green-100 text-green-800'
                          }>
                            {comp.threatLevel || 'low'}
                          </Badge>
                        </TableCell>
                        <TableCell>
                          <Link href={`/competitors/${comp.id}`}>
                            <Button size="sm" variant="ghost">Analyze</Button>
                          </Link>
                        </TableCell>
                      </TableRow>
                    );
                  })}
                </TableBody>
              </Table>
            </CardContent>
          </Card>

          {/* Key Advantages */}
          <div className="grid md:grid-cols-2 gap-4">
            <Card className="border-green-500">
              <CardHeader>
                <CardTitle className="text-green-600 flex items-center gap-2">
                  <CheckCircle2 className="h-5 w-5" />
                  Tulip Competitive Advantages
                </CardTitle>
              </CardHeader>
              <CardContent>
                <ul className="space-y-2">
                  <li className="flex items-start gap-2">
                    <span className="text-green-600 mt-1">✓</span>
                    <span className="text-sm">Unicorn status ($1.3B valuation) - only platform with this scale</span>
                  </li>
                  <li className="flex items-start gap-2">
                    <span className="text-green-600 mt-1">✓</span>
                    <span className="text-sm">Strongest AI suite: Composer + Agents + Akooda acquisition</span>
                  </li>
                  <li className="flex items-start gap-2">
                    <span className="text-green-600 mt-1">✓</span>
                    <span className="text-sm">No-code platform - fastest time-to-value (weeks vs months)</span>
                  </li>
                  <li className="flex items-start gap-2">
                    <span className="text-green-600 mt-1">✓</span>
                    <span className="text-sm">Mitsubishi partnership opens global enterprise market</span>
                  </li>
                  <li className="flex items-start gap-2">
                    <span className="text-green-600 mt-1">✓</span>
                    <span className="text-sm">$272.5M funding - strongest runway in category</span>
                  </li>
                </ul>
              </CardContent>
            </Card>

            <Card className="border-orange-500">
              <CardHeader>
                <CardTitle className="text-orange-600 flex items-center gap-2">
                  <AlertTriangle className="h-5 w-5" />
                  Watch List - Competitive Threats
                </CardTitle>
              </CardHeader>
              <CardContent>
                <ul className="space-y-2">
                  {competitorsOnly
                    .filter(c => c.threatLevel === 'high' || c.threatLevel === 'medium')
                    .map(c => (
                      <li key={c.id} className="flex items-start gap-2 pb-2 border-b last:border-0">
                        <span className="text-orange-600 mt-1">⚠</span>
                        <div className="text-sm flex-1">
                          <span className="font-semibold">{c.name}</span>
                          <span className="text-muted-foreground"> ({c.category})</span>
                          <p className="text-xs text-muted-foreground mt-1">
                            {c.positioning.substring(0, 100)}...
                          </p>
                        </div>
                      </li>
                    ))}
                </ul>
              </CardContent>
            </Card>
          </div>
        </TabsContent>

        <TabsContent value="comparison">
          <Card>
            <CardHeader>
              <CardTitle>Detailed Head-to-Head Analysis</CardTitle>
              <CardDescription>Feature-by-feature comparison coming soon</CardDescription>
            </CardHeader>
            <CardContent>
              <p className="text-muted-foreground">This tab will show detailed feature comparisons, customer overlap, win/loss analysis, and pricing strategies.</p>
            </CardContent>
          </Card>
        </TabsContent>

        <TabsContent value="sources">
          <Card>
            <CardHeader>
              <CardTitle>Data Sources & Attribution</CardTitle>
              <CardDescription>Where all competitive intelligence data comes from</CardDescription>
            </CardHeader>
            <CardContent>
              <div className="space-y-4">
                {[tulip, ...competitorsOnly].filter(Boolean).map(comp => (
                  <div key={comp.id} className="p-4 border rounded-lg">
                    <h3 className="font-semibold mb-3">{comp.name}</h3>
                    <div className="grid md:grid-cols-2 gap-4 text-sm">
                      <div>
                        <span className="text-muted-foreground">Revenue:</span>
                        <span className="ml-2 font-mono">{comp.revenue}</span>
                        <a href="#" className="ml-2 text-xs text-blue-600 hover:underline">
                          Source <ExternalLink className="inline h-3 w-3" />
                        </a>
                      </div>
                      <div>
                        <span className="text-muted-foreground">Employees:</span>
                        <span className="ml-2 font-mono">{comp.employees}</span>
                        <a href="#" className="ml-2 text-xs text-blue-600 hover:underline">
                          Source <ExternalLink className="inline h-3 w-3" />
                        </a>
                      </div>
                      <div>
                        <span className="text-muted-foreground">Funding:</span>
                        <span className="ml-2 font-mono">{comp.funding}</span>
                        <a href="#" className="ml-2 text-xs text-blue-600 hover:underline">
                          Source <ExternalLink className="inline h-3 w-3" />
                        </a>
                      </div>
                      <div>
                        <span className="text-muted-foreground">Valuation:</span>
                        <span className="ml-2 font-mono">{comp.valuation}</span>
                        <a href="#" className="ml-2 text-xs text-blue-600 hover:underline">
                          Source <ExternalLink className="inline h-3 w-3" />
                        </a>
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            </CardContent>
          </Card>
        </TabsContent>
      </Tabs>

      {/* Quick Actions */}
      <div className="flex gap-4 justify-center">
        <Link href="/">
          <Button variant="outline">View Full Dashboard</Button>
        </Link>
        <Link href="/signals">
          <Button variant="outline">All Competitive Signals</Button>
        </Link>
        <Link href="/battlecard">
          <Button variant="outline">Generate Battlecards</Button>
        </Link>
      </div>
    </div>
  );
}