'use client'

import { useState, useEffect } from 'react';
import Link from 'next/link';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle, DialogTrigger } from '@/components/ui/dialog';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { TrendingUp, TrendingDown, Mail, Target, AlertTriangle, ArrowLeft, Activity, Pencil, Check, X } from 'lucide-react';
import { toast } from 'sonner';

export default function TulipCommandCenter() {
  const [competitors, setCompetitors] = useState([]);
  const [signals, setSignals] = useState([]);
  const [tulip, setTulip] = useState(null);
  const [loading, setLoading] = useState(true);
  const [emailDialogOpen, setEmailDialogOpen] = useState(false);
  const [emailRecipients, setEmailRecipients] = useState('leadership-team@tulip.co');

  // Inline edit state for revenue
  const [editingRevenue, setEditingRevenue] = useState(false);
  const [revenueDraft, setRevenueDraft] = useState('');
  const [savingRevenue, setSavingRevenue] = useState(false);

  useEffect(() => {
    loadData();
  }, []);

  async function loadData() {
    try {
      const [competitorsRes, signalsRes, tulipRes] = await Promise.all([
        fetch('/api/competitors'),
        fetch('/api/signals'),
        fetch('/api/tulip-profile'),
      ]);
      setCompetitors(await competitorsRes.json());
      setSignals(await signalsRes.json());
      setTulip(await tulipRes.json());
    } catch (error) {
      console.error('Error loading data:', error);
      toast.error('Failed to load data');
    } finally {
      setLoading(false);
    }
  }

  async function saveRevenue() {
    setSavingRevenue(true);
    try {
      const r = await fetch('/api/tulip-profile', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ revenue: revenueDraft }),
      });
      if (!r.ok) throw new Error('save failed');
      const updated = await r.json();
      setTulip(updated);
      setEditingRevenue(false);
      toast.success('Revenue updated');
    } catch (e) {
      toast.error('Failed to save revenue');
    } finally {
      setSavingRevenue(false);
    }
  }

  function buildEmailBody() {
    // Competitor-focused digest — no Tulip metrics
    const competitorsOnly = competitors.filter(c => c.id !== 'tulip');
    const sorted = [...competitorsOnly].sort((a, b) => (b.threatScore || 0) - (a.threatScore || 0));
    const top5 = sorted.slice(0, 5);
    const critical = sorted.filter(c => (c.threatScore || 0) >= 70);

    const weekAgo = new Date(); weekAgo.setDate(weekAgo.getDate() - 7);
    const recentSignals = signals.filter(s => new Date(s.timestamp) > weekAgo);

    const subject = `Weekly Competitive Intelligence Digest — ${new Date().toLocaleDateString()}`;
    const body = `TULIP COMPETITIVE INTELLIGENCE — WEEKLY DIGEST
${new Date().toLocaleDateString()}

═══════════════════════════════════════════════
🎯 COMPETITIVE LANDSCAPE — TOP 5 BY THREAT
═══════════════════════════════════════════════
${top5.map((c, idx) => `
${idx + 1}. ${c.name} — ${c.category}
   Threat Score:   ${c.threatScore ?? '—'}/100
   Revenue:        ${c.revenue || '—'}
   Employees:      ${c.employees || '—'}
   Valuation:      ${c.valuation || 'Private'}
   Tulip angle:    ${(c.tulipRelevance || c.tulipCompetitiveAngle || '—').slice(0, 140)}
`).join('')}

═══════════════════════════════════════════════
⚠️  CRITICAL WATCHLIST — ${critical.length} competitors at threat ≥ 70
═══════════════════════════════════════════════
${critical.length > 0 ? critical.map(c => `
• ${c.name} (${c.threatScore}/100) — ${c.category}
  ${(c.positioning || '').slice(0, 150)}
`).join('') : 'No competitors at threat ≥ 70 this week.'}

═══════════════════════════════════════════════
📰 NEW COMPETITIVE SIGNALS — LAST 7 DAYS
═══════════════════════════════════════════════
${recentSignals.length > 0 ? recentSignals.map(s => `
• [${(s.severity || '').toUpperCase()}] ${s.competitorName}: ${s.title}
  ${(s.summary || '').slice(0, 150)}
  Recommended: ${(s.recommendedAction || '').slice(0, 120)}
`).join('') : 'No new signals in the past week.'}

═══════════════════════════════════════════════
🔗 NEXT STEPS
═══════════════════════════════════════════════
View Full Dashboard:     ${typeof window !== 'undefined' ? window.location.origin : ''}
Strategic Insights:      ${typeof window !== 'undefined' ? window.location.origin : ''}#strategic-insights
Battlecards:             ${typeof window !== 'undefined' ? window.location.origin : ''}/battlecard

—
Generated by Tulip Competitive Intelligence Command Center`;
    return { subject, body };
  }

  function sendWeeklyDigest() {
    const { subject, body } = buildEmailBody();
    const mailtoUrl = `mailto:${emailRecipients}?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;
    window.location.href = mailtoUrl;
    toast.success('Opening email client with weekly digest…');
    setEmailDialogOpen(false);
  }

  if (loading) {
    return (
      <div className="flex items-center justify-center min-h-screen bg-white">
        <div className="text-center">
          <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-gray-900 mx-auto"></div>
          <p className="mt-4 text-sm text-gray-500 uppercase tracking-widest">Loading Tulip Command Center…</p>
        </div>
      </div>
    );
  }

  const competitorsOnly = competitors.filter(c => c.id !== 'tulip');

  // Compute relative metrics
  const sortedByThreat = [...competitorsOnly].sort((a, b) => (b.threatScore || 0) - (a.threatScore || 0));
  const criticalCount = competitorsOnly.filter(c => (c.threatScore || 0) >= 70).length;
  const highSeverityRecent = signals.filter(s => {
    const d = new Date(s.timestamp);
    const thirty = new Date(); thirty.setDate(thirty.getDate() - 30);
    return d > thirty && (s.severity || '').toLowerCase() === 'high';
  }).length;

  // Market rank: how many competitors are above Tulip in revenue
  const parseRev = (r) => {
    if (!r) return 0;
    const m = r.match(/\$([\d.]+)\s*([BM])/i);
    if (!m) return 0;
    return parseFloat(m[1]) * (m[2].toUpperCase() === 'B' ? 1000 : 1);
  };
  const tulipRevM = parseRev(tulip?.revenue);
  const competitorsAhead = competitorsOnly.filter(c => parseRev(c.revenue) > tulipRevM).length;
  const marketRank = competitorsAhead + 1;

  const threatBadge = (score) => {
    if (score >= 70) return 'bg-red-50 text-red-700 border-red-200';
    if (score >= 50) return 'bg-amber-50 text-amber-800 border-amber-200';
    if (score >= 30) return 'bg-gray-50 text-gray-700 border-gray-300';
    return 'bg-emerald-50 text-emerald-800 border-emerald-200';
  };

  return (
    <div className="min-h-screen bg-white">
      <div className="container mx-auto px-8 py-10 max-w-7xl">
        {/* Header */}
        <Link href="/">
          <Button variant="ghost" className="mb-4 -ml-3">
            <ArrowLeft className="mr-2 h-4 w-4" />
            Back to Dashboard
          </Button>
        </Link>

        <div className="flex items-start justify-between mb-10 flex-wrap gap-4">
          <div>
            <h1 className="text-5xl font-light tracking-tight text-gray-900 mb-2">Tulip Command Center</h1>
            <p className="text-base text-gray-500">Executive view — Tulip's position relative to {competitorsOnly.length} tracked competitors</p>
          </div>
          <div className="flex gap-2">
            <Link href="/email-agents">
              <Button variant="outline" className="border-gray-300">
                <Activity className="mr-2 h-4 w-4" />
                Email Agents
              </Button>
            </Link>
            <Dialog open={emailDialogOpen} onOpenChange={setEmailDialogOpen}>
              <DialogTrigger asChild>
                <Button className="bg-black hover:bg-gray-900 text-white">
                  <Mail className="mr-2 h-4 w-4" />
                  Send Weekly Digest
                </Button>
              </DialogTrigger>
              <DialogContent>
                <DialogHeader>
                  <DialogTitle>Send Weekly Competitive Digest</DialogTitle>
                  <DialogDescription>
                    Generates a digest of competitor activity — no internal Tulip metrics included.
                  </DialogDescription>
                </DialogHeader>
                <div className="grid gap-4 py-4">
                  <div className="grid gap-2">
                    <Label htmlFor="recipients">Recipients</Label>
                    <Input id="recipients" value={emailRecipients} onChange={(e) => setEmailRecipients(e.target.value)} />
                    <p className="text-xs text-gray-500">Separate multiple emails with commas</p>
                  </div>
                  <div className="p-4 bg-gray-50 border border-gray-200 text-sm">
                    <p className="font-medium mb-2">Digest will include:</p>
                    <ul className="space-y-1 text-gray-700">
                      <li>• Top 5 competitors ranked by threat</li>
                      <li>• Critical watchlist (threat ≥ 70)</li>
                      <li>• New signals from last 7 days</li>
                      <li>• No Tulip-internal metrics — competitor data only</li>
                    </ul>
                  </div>
                </div>
                <DialogFooter>
                  <Button variant="outline" onClick={() => setEmailDialogOpen(false)}>Cancel</Button>
                  <Button onClick={sendWeeklyDigest} className="bg-black text-white">Open in Email Client</Button>
                </DialogFooter>
              </DialogContent>
            </Dialog>
          </div>
        </div>

        {/* Relative-position stat cards — no valuation front and center */}
        <div className="grid gap-0 md:grid-cols-4 mb-10 border border-gray-900 divide-x divide-gray-900">
          <div className="p-5">
            <div className="text-[10px] uppercase tracking-widest text-gray-500 mb-2">Market Rank (by revenue)</div>
            <div className="text-3xl font-light text-gray-900">#{marketRank}</div>
            <p className="text-xs text-gray-500 mt-1">of {competitorsOnly.length + 1} tracked vendors</p>
          </div>
          <div className="p-5">
            <div className="text-[10px] uppercase tracking-widest text-gray-500 mb-2">Larger Competitors</div>
            <div className="text-3xl font-light text-gray-900">{competitorsAhead}</div>
            <p className="text-xs text-gray-500 mt-1">by revenue scale</p>
          </div>
          <div className="p-5">
            <div className="text-[10px] uppercase tracking-widest text-red-700 mb-2">Critical Watchlist</div>
            <div className="text-3xl font-light text-gray-900 flex items-baseline gap-2">
              {criticalCount}
              <span className="h-2 w-2 rounded-full bg-red-600"></span>
            </div>
            <p className="text-xs text-gray-500 mt-1">competitors at threat ≥ 70</p>
          </div>
          <div className="p-5">
            <div className="text-[10px] uppercase tracking-widest text-gray-500 mb-2">High-Severity Moves</div>
            <div className="text-3xl font-light text-gray-900">{highSeverityRecent}</div>
            <p className="text-xs text-gray-500 mt-1">last 30 days</p>
          </div>
        </div>

        {/* Tulip self-profile — compact, inline editable */}
        <Card className="border border-gray-200 mb-10 rounded-none">
          <div className="p-5 grid md:grid-cols-5 gap-5 items-center">
            <div>
              <div className="text-[10px] uppercase tracking-widest text-gray-500 mb-1">Tulip Profile</div>
              <p className="text-base font-medium text-gray-900">{tulip?.name}</p>
              <p className="text-xs text-gray-500">{tulip?.category}</p>
            </div>
            {/* Inline editable Revenue */}
            <div>
              <div className="text-[10px] uppercase tracking-widest text-gray-500 mb-1">Revenue (ARR)</div>
              {editingRevenue ? (
                <div className="flex items-center gap-1">
                  <Input
                    value={revenueDraft}
                    onChange={(e) => setRevenueDraft(e.target.value)}
                    className="h-8 text-sm w-24"
                    placeholder="$50M"
                    autoFocus
                    onKeyDown={(e) => {
                      if (e.key === 'Enter') saveRevenue();
                      if (e.key === 'Escape') setEditingRevenue(false);
                    }}
                  />
                  <Button size="sm" variant="ghost" onClick={saveRevenue} disabled={savingRevenue} className="h-8 w-8 p-0">
                    <Check className="h-4 w-4 text-emerald-700" />
                  </Button>
                  <Button size="sm" variant="ghost" onClick={() => setEditingRevenue(false)} className="h-8 w-8 p-0">
                    <X className="h-4 w-4 text-gray-500" />
                  </Button>
                </div>
              ) : (
                <button
                  className="group inline-flex items-center gap-2 text-base font-medium text-gray-900 hover:text-emerald-700 transition-colors"
                  onClick={() => { setRevenueDraft(tulip?.revenue || ''); setEditingRevenue(true); }}
                  title="Click to edit"
                >
                  {tulip?.revenue || '—'}
                  <Pencil className="h-3 w-3 text-gray-300 group-hover:text-emerald-700 transition-colors" />
                </button>
              )}
            </div>
            <div>
              <div className="text-[10px] uppercase tracking-widest text-gray-500 mb-1">Employees</div>
              <p className="text-base font-medium text-gray-900">{tulip?.employees}</p>
            </div>
            <div>
              <div className="text-[10px] uppercase tracking-widest text-gray-500 mb-1">Funding</div>
              <p className="text-base font-medium text-gray-900">{tulip?.funding}</p>
            </div>
            <div>
              <div className="text-[10px] uppercase tracking-widest text-gray-500 mb-1">Valuation</div>
              <p className="text-base font-medium text-gray-900">{tulip?.valuation}</p>
            </div>
          </div>
        </Card>

        {/* Tabs */}
        <Tabs defaultValue="snapshot" className="space-y-4">
          <TabsList className="bg-gray-100 border-b border-gray-200">
            <TabsTrigger value="snapshot">Market Snapshot</TabsTrigger>
            <TabsTrigger value="threats">Top Threats</TabsTrigger>
          </TabsList>

          {/* SNAPSHOT — competitor-relative view */}
          <TabsContent value="snapshot" className="space-y-4">
            <Card className="border border-gray-200 rounded-none">
              <CardHeader className="border-b border-gray-100">
                <CardTitle className="text-xl font-light">Tulip vs Market</CardTitle>
                <CardDescription>Competitor positions relative to Tulip — sorted by threat</CardDescription>
              </CardHeader>
              <CardContent className="p-0">
                <Table>
                  <TableHeader>
                    <TableRow className="bg-gray-50 border-b border-gray-200">
                      <TableHead className="text-[10px] uppercase tracking-widest text-gray-500">Company</TableHead>
                      <TableHead className="text-[10px] uppercase tracking-widest text-gray-500">Revenue</TableHead>
                      <TableHead className="text-[10px] uppercase tracking-widest text-gray-500">vs Tulip</TableHead>
                      <TableHead className="text-[10px] uppercase tracking-widest text-gray-500">Employees</TableHead>
                      <TableHead className="text-[10px] uppercase tracking-widest text-gray-500">Valuation</TableHead>
                      <TableHead className="text-[10px] uppercase tracking-widest text-gray-500">Threat</TableHead>
                      <TableHead></TableHead>
                    </TableRow>
                  </TableHeader>
                  <TableBody>
                    {/* Tulip row — minimal, just for reference */}
                    <TableRow className="bg-gray-50 border-b border-gray-200">
                      <TableCell className="font-medium text-gray-900">
                        {tulip?.name}
                        <span className="ml-2 text-[10px] uppercase tracking-wider text-gray-500 border border-gray-300 px-1.5 py-0.5">You</span>
                      </TableCell>
                      <TableCell className="font-medium text-gray-900">{tulip?.revenue}</TableCell>
                      <TableCell className="text-xs text-gray-400">—</TableCell>
                      <TableCell className="text-gray-700">{tulip?.employees}</TableCell>
                      <TableCell className="text-gray-700">{tulip?.valuation}</TableCell>
                      <TableCell><span className="text-xs text-gray-400">—</span></TableCell>
                      <TableCell></TableCell>
                    </TableRow>
                    {sortedByThreat.map((comp) => {
                      const compRev = parseRev(comp.revenue);
                      const diff = compRev - tulipRevM;
                      const isAhead = diff > 0;
                      const diffStr = Math.abs(diff) >= 1000 ? `$${(Math.abs(diff)/1000).toFixed(1)}B` : `$${Math.abs(diff).toFixed(0)}M`;
                      return (
                        <TableRow key={comp.id} className="border-b border-gray-100 hover:bg-gray-50/70">
                          <TableCell className="font-medium text-gray-900">
                            <Link href={`/competitors/${comp.id}`} className="hover:underline">{comp.name}</Link>
                            <div className="text-[11px] text-gray-400 font-normal mt-0.5">{comp.category}</div>
                          </TableCell>
                          <TableCell className="text-gray-900">{comp.revenue || '—'}</TableCell>
                          <TableCell>
                            {compRev === 0 ? (
                              <span className="text-xs text-gray-400">—</span>
                            ) : isAhead ? (
                              <span className="inline-flex items-center gap-1 text-xs text-red-700">
                                <TrendingUp className="h-3 w-3" />
                                +{diffStr} ahead
                              </span>
                            ) : (
                              <span className="inline-flex items-center gap-1 text-xs text-emerald-700">
                                <TrendingDown className="h-3 w-3" />
                                {diffStr} behind
                              </span>
                            )}
                          </TableCell>
                          <TableCell className="text-gray-700">{comp.employees || '—'}</TableCell>
                          <TableCell className="text-gray-700 text-sm">{comp.valuation || 'Private'}</TableCell>
                          <TableCell>
                            <span className={`inline-flex items-center gap-1 px-2 py-0.5 text-[10px] font-medium uppercase tracking-wider border ${threatBadge(comp.threatScore || 0)}`}>
                              {comp.threatScore || 0}
                            </span>
                          </TableCell>
                          <TableCell>
                            <Link href={`/competitors/${comp.id}`}>
                              <Button size="sm" variant="ghost" className="text-gray-900">View →</Button>
                            </Link>
                          </TableCell>
                        </TableRow>
                      );
                    })}
                  </TableBody>
                </Table>
              </CardContent>
            </Card>
          </TabsContent>

          {/* THREATS — focused view */}
          <TabsContent value="threats">
            <Card className="border border-gray-900 rounded-none">
              <CardHeader className="border-b border-gray-200">
                <CardTitle className="flex items-center gap-2 text-xl font-light">
                  <AlertTriangle className="h-5 w-5 text-red-600" />
                  Top Threats — Critical Watchlist
                </CardTitle>
                <CardDescription>Competitors at threat score ≥ 70</CardDescription>
              </CardHeader>
              <CardContent className="p-0 divide-y divide-gray-100">
                {sortedByThreat.filter(c => (c.threatScore || 0) >= 70).length === 0 && (
                  <p className="p-6 text-sm text-gray-500">No competitors currently on the critical watchlist.</p>
                )}
                {sortedByThreat.filter(c => (c.threatScore || 0) >= 70).map(c => (
                  <div key={c.id} className="p-5 flex items-start gap-4">
                    <div className="flex-shrink-0">
                      <span className={`inline-flex items-center justify-center w-12 h-12 text-xl font-light border ${threatBadge(c.threatScore)}`}>
                        {c.threatScore}
                      </span>
                    </div>
                    <div className="flex-1 min-w-0">
                      <div className="flex items-center gap-2 mb-1">
                        <Link href={`/competitors/${c.id}`} className="font-medium text-gray-900 hover:underline">{c.name}</Link>
                        <span className="text-[11px] uppercase tracking-wider text-gray-500">{c.category}</span>
                      </div>
                      <p className="text-sm text-gray-700 leading-snug line-clamp-2">{(c.tulipRelevance || c.positioning || '').slice(0, 220)}</p>
                      <div className="flex items-center gap-3 mt-2 text-[11px] text-gray-500">
                        <span>Revenue · <strong className="text-gray-700">{c.revenue || '—'}</strong></span>
                        <span>Employees · <strong className="text-gray-700">{c.employees || '—'}</strong></span>
                        <span>Geography · <strong className="text-gray-700">{c.geography || c.strongGeography || '—'}</strong></span>
                      </div>
                    </div>
                    <Link href={`/competitors/${c.id}`}>
                      <Button size="sm" variant="outline" className="border-gray-300">Battle Plan →</Button>
                    </Link>
                  </div>
                ))}
              </CardContent>
            </Card>
          </TabsContent>
        </Tabs>
      </div>
    </div>
  );
}
